name: Update GitHub Profile Stats

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=ammarc0der&show_icons=true&hide_border=true&theme=tokyonight
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=ammarc0der&layout=compact&langs_count=8&hide_border=true&theme=tokyonight
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Ecommerce Project Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=ammarc0der&repo=ecommerce_flutter&theme=tokyonight&hide_border=true
          path: profile/ecommerce.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate ToDayDo Project Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=ammarc0der&repo=ToDayDo&theme=tokyonight&hide_border=true
          path: profile/todaydo.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Register App Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=ammarc0der&repo=register_app&theme=tokyonight&hide_border=true
          path: profile/register-app.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit generated cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/*.svg

          git commit -m "Update GitHub profile stats" || exit 0

          git pushname: Update GitHub Profile Stats

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Generate GitHub Stats
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: stats
          options: username=ammarc0der&show_icons=true&hide_border=true&theme=tokyonight
          path: profile/stats.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Top Languages
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: top-langs
          options: username=ammarc0der&layout=compact&langs_count=8&hide_border=true&theme=tokyonight
          path: profile/top-langs.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Ecommerce Project Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=ammarc0der&repo=ecommerce_flutter&theme=tokyonight&hide_border=true
          path: profile/ecommerce.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate ToDayDo Project Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=ammarc0der&repo=ToDayDo&theme=tokyonight&hide_border=true
          path: profile/todaydo.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate Register App Card
        uses: stats-organization/github-readme-stats-action@v2
        with:
          card: pin
          options: username=ammarc0der&repo=register_app&theme=tokyonight&hide_border=true
          path: profile/register-app.svg
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit generated cards
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add profile/*.svg

          git commit -m "Update GitHub profile stats" || exit 0

          git push
